//exist for @flow checking, due to actionCreator & reducer won't pop any alert.
const INIT_ITEMS = 'INIT_ITEMS';
const ADD_ITEM = 'ADD_ITEM';//use const to report error.
const DEL_ITEM = 'DEL_ITEM';
const UPDATE_ITEM = 'UPDATE_ITEM';
const SEARCH_ITEMS = 'SEARCH_ITEM';
const SORT_ITEMS = 'SORT_ITEM';
const TOGGLE_FILTER = 'TOGGLE_FILTER';
const FETCH_LOAD_ITEMS = 'FETCH_LOAD_ITEMS';
const FETCH_ADD_ITEM = 'FETCH_ADD_ITEM';
const FETCH_DEL_ITEM = 'FETCH_DEL_ITEM';
const FETCH_UPDATE_ITEM = 'FETCH_UPDATE_ITEM';
export { INIT_ITEMS, ADD_ITEM, UPDATE_ITEM, DEL_ITEM, SEARCH_ITEMS, SORT_ITEMS, TOGGLE_FILTER, FETCH_UPDATE_ITEM, FETCH_ADD_ITEM, FETCH_DEL_ITEM, FETCH_LOAD_ITEMS };